-- 0009_blog_posts.sql
-- Auto AI Blog: posts generated by the backend and served publicly on the
-- /blog routes.
--
-- Access model:
--   * Writers = AI backend via the service_role key (bypasses RLS).
--   * Readers = anon + authenticated, SELECT only, published posts only
--     (published_at <= now()). No insert/update/delete policies exist for
--     public roles, so anon/authenticated can never write.
--   * published_at semantics: null = unpublished draft, future timestamp =
--     scheduled post, now() (default) = live immediately.

create table public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 300),
  -- URL slug; unique constraint doubles as the lookup index for
  -- /blog/<slug> routing. Pipeline must slugify (lowercase, [a-z0-9-]).
  slug text not null unique
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  content text not null default '',   -- main article body (HTML or Markdown)
  excerpt text not null default '',
  cover_image_url text,
  tags text[] not null default '{}'::text[],
  keywords text[] not null default '{}'::text[],
  published_at timestamptz default now(),
  created_at timestamptz not null default now()
);

-- Feed query: order published posts newest-first. Partial index skips
-- unpublished drafts, which every public read filters out anyway.
create index blog_posts_published_idx
  on public.blog_posts (published_at desc)
  where published_at is not null;

-- Tag / keyword filtering (contains-any queries).
create index blog_posts_tags_idx
  on public.blog_posts using gin (tags);
create index blog_posts_keywords_idx
  on public.blog_posts using gin (keywords);

alter table public.blog_posts enable row level security;

create policy "blog_posts_select_published"
  on public.blog_posts for select
  to anon, authenticated
  using (published_at is not null and published_at <= now());
